shards:
  lpl:
    host: localhost
    port: 5432
    dbname: shard_lpl_db
    user: postgres
    password: ""

  lck:
    host: localhost
    port: 5433
    dbname: shard_lck_db
    user: postgres
    password: ""

